Repository ExchangeUnion/xud, pull requests merged in 2018-11, with the labels that each got.

#624 refactor(orderbook): change ORDER_NOT_FOUND msg
  lib/orderbook/TradingPair.ts
  lib/orderbook/errors.ts
  test/unit/TradingPair.spec.ts
Labels: in progress, logging

#632 feat(rpc): add UNAVAILABLE grpc error status code
  lib/grpc/GrpcService.ts
  lib/lndclient/LndClient.ts
  lib/lndclient/errors.ts
Labels: error handling, grpc, in progress

#630 chore: update typedoc script and run on version
  package.json
Labels: build, in progress

#629 chore: update typedoc dependency
  package-lock.json
  package.json
Labels: build, in progress

#631 refactor(orderbook): localId does not exist error
  lib/grpc/GrpcService.ts
  lib/orderbook/OrderBook.ts
  lib/orderbook/errors.ts
Labels: error handling, in progress

#600 feat(cli): show table for getorders
  bin/xucli
  lib/cli/command.ts
  lib/cli/commands/addcurrency.ts
  lib/cli/commands/addpair.ts
  lib/cli/commands/ban.ts
  lib/cli/commands/cancelorder.ts
  lib/cli/commands/channelbalance.ts
  lib/cli/commands/connect.ts
  lib/cli/commands/executeswap.ts
  lib/cli/commands/getinfo.ts
  lib/cli/commands/getnodeinfo.ts
  lib/cli/commands/getorders.ts
  lib/cli/commands/listpairs.ts
  lib/cli/commands/listpeers.ts
  lib/cli/commands/removecurrency.ts
  lib/cli/commands/removepair.ts
  lib/cli/commands/shutdown.ts
  lib/cli/commands/unban.ts
  lib/cli/utils.ts
  package-lock.json
  package.json
  test/integration/Command.spec.ts
  test/unit/Command.spec.ts
Labels: in progress

#641 chore: update typescript dependency
  package-lock.json
  package.json
Labels: build, in progress

#646 chore: add script to generate changelog
  .npmrc
  package-lock.json
  package.json
Labels: build, in progress

#651 chore: remove bin/{
  bin/{
Labels: in progress

#626 feat(orderbook/swaps): release order hold
  lib/orderbook/OrderBook.ts
  lib/orderbook/TradingPair.ts
  lib/p2p/Pool.ts
  lib/service/Service.ts
  lib/types/orders.ts
  test/integration/OrderBook.spec.ts
  test/unit/TradingPair.spec.ts
Labels: error handling, in progress, order book, swaps

#627 feat(swaps): calculate swap amounts locally
  lib/orderbook/OrderBook.ts
  lib/p2p/packets/types/SwapRequestPacket.ts
  lib/swaps/Swaps.ts
  lib/swaps/types.ts
  lib/types/db.ts
  lib/types/enums.ts
  test/unit/Swaps.spec.ts
Labels: in progress, swaps

#628 feat(swaps): check that swap request is valid
  lib/orderbook/OrderBook.ts
  lib/swaps/Swaps.ts
  lib/types/enums.ts
  test/unit/Swaps.spec.ts
Labels: in progress, swaps

#610 refactor(swaps): renaming packets & properties
  docs/api.md
  lib/db/models/SwapDeal.ts
  lib/grpc/GrpcService.ts
  lib/orderbook/OrderBook.ts
  lib/p2p/Parser.ts
  lib/p2p/Pool.ts
  lib/p2p/packets/types/SwapAcceptedPacket.ts
  lib/p2p/packets/types/SwapCompletePacket.ts
  lib/p2p/packets/types/SwapFailedPacket.ts
  lib/p2p/packets/types/SwapRequestPacket.ts
  lib/p2p/packets/types/index.ts
  lib/proto/xudrpc.swagger.json
  lib/service/Service.ts
  lib/swaps/SwapRepository.ts
  lib/swaps/Swaps.ts
  lib/swaps/types.ts
  lib/types/db.ts
  lib/types/orderBook.ts
  lib/types/orders.ts
  proto/xudrpc.proto
  test/unit/Swaps.spec.ts
Labels: code quality, in progress, swaps

#623 Add Order & Trade Models, restructure & rename order types
  lib/db/DB.ts
  lib/db/models/Currency.ts
  lib/db/models/Node.ts
  lib/db/models/Order.ts
  lib/db/models/Pair.ts
  lib/db/models/ReputationEvent.ts
  lib/db/models/SwapDeal.ts
  lib/db/models/Trade.ts
  lib/grpc/GrpcService.ts
  lib/orderbook/OrderBook.ts
  lib/orderbook/OrderBookRepository.ts
  lib/orderbook/TradingPair.ts
  lib/p2p/Pool.ts
  lib/raidenclient/RaidenClient.ts
  lib/service/Service.ts
  lib/swaps/SwapRepository.ts
  lib/swaps/Swaps.ts
  lib/swaps/types.ts
  lib/types/db.ts
  lib/types/matchingEngine.ts
  lib/types/orderBook.ts
  lib/types/orders.ts
  test/integration/OrderBook.spec.ts
  test/unit/DB.spec.ts
  test/unit/TradingPair.spec.ts
Labels: automated tests, code quality, database, in progress, order book

#634 refactor(peer) removing banning logic
  lib/p2p/NodeList.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/types/enums.ts
Labels: in progress

#645 Refactor(Order proto) added hold value
  docs/api.md
  lib/grpc/GrpcService.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  proto/xudrpc.proto
Labels: in progress

#642 Refactor(Swaps.ts) checks if r_hash exists before making swap
  lib/swaps/Swaps.ts
Labels: in progress

#650 feat(swaps): verify route before executing the swap
  lib/swaps/Swaps.ts
  package-lock.json
  package.json
  test/integration/Swap.spec.ts
  test/utils.ts
Labels: in progress

#658 feat: disconnecting packet
  lib/p2p/NodeList.ts
  lib/p2p/Parser.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/p2p/packets/PacketType.ts
  lib/p2p/packets/types/DisconnectingPacket.ts
  lib/p2p/packets/types/index.ts
  lib/types/enums.ts
Labels: in progress

#665 feat(db): join swapdeal to order & node
  lib/db/models/SwapDeal.ts
  lib/grpc/GrpcService.ts
  lib/orderbook/OrderBookRepository.ts
  lib/p2p/Pool.ts
  lib/swaps/SwapRepository.ts
  lib/types/db.ts
  test/unit/DB.spec.ts
Labels: database, in progress

#667 refactor(orderbook): set localId to global id
  lib/orderbook/OrderBook.ts
  test/integration/OrderBook.spec.ts
Labels: in progress, order book

#633 Partial swap
  lib/swaps/Swaps.ts
Labels: in progress

#659 feat(OrderBook.ts) persist trades to DB
  lib/orderbook/OrderBook.ts
  lib/orderbook/OrderBookRepository.ts
Labels: in progress

#662 Streamline matching logic and add log statements
  lib/orderbook/TradingPair.ts
  test/integration/OrderBook.spec.ts
  test/unit/TradingPair.spec.ts
Labels: in progress, logging, order book, performance

#678 test: add hold value to orders
  test/unit/Command.spec.ts
Labels: automated tests, build, in progress

#669 feat(cli): format buy & sell output
  lib/cli/commands/getorders.ts
  lib/cli/utils.ts
Labels: command line (CLI), in progress

#672 perf: use async fs & crypto methods
  lib/Config.ts
  lib/Xud.ts
  lib/db/DB.ts
  lib/grpc/GrpcServer.ts
  lib/grpc/webproxy/GrpcWebProxyServer.ts
  lib/lndclient/LndClient.ts
  lib/nodekey/NodeKey.ts
  lib/swaps/Swaps.ts
  lib/utils/fsUtils.ts
  lib/utils/utils.ts
  test/integration/Pool.spec.ts
  test/unit/NodeKey.spec.ts
Labels: in progress, performance

#692 fix(lnd): don't default lnd clients as disabled
  lib/BaseClient.ts
  lib/Xud.ts
  lib/lndclient/LndClient.ts
  lib/raidenclient/RaidenClient.ts
Labels: bug, in progress

#691 Docker auto-generated files added to .gitignore
  .gitignore
Labels: docker

#683 feat(db): set null price for market orders
  lib/db/models/Order.ts
  test/unit/DB.spec.ts
Labels: database, in progress

#702 refactor(p2p): remove PeerList class
  lib/p2p/PeerList.ts
  lib/p2p/Pool.ts
  test/integration/Pool.spec.ts
Labels: code quality, in progress, p2p

#701 fix(p2p): cancel retry connection timer
  lib/p2p/Peer.ts
Labels: bug, in progress, p2p

#697 feat(orderbook): don’t match with quantity on hold
  lib/orderbook/TradingPair.ts
  test/unit/TradingPair.spec.ts
Labels: in progress, order book
