Repository ExchangeUnion/xud, pull requests merged in 2018-10, with the labels that each got.

#526 Added fetching supported pairs for GetOrdersPacket
  lib/orderbook/OrderBook.ts
  lib/p2p/Pool.ts
  lib/p2p/packets/types/GetOrdersPacket.ts
  lib/p2p/packets/types/index.ts
Labels: in progress, p2p

#518 feat: update handshake on lnd pubkey change
  lib/Xud.ts
  lib/lndclient/LndClient.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/types/p2p.ts
Labels: in progress, lightning, p2p

#509 doc: Exchange Union -> XUD
  README.md
Labels: in progress

#531 Disable initdb for web proxy tests & prevent new connections after closing pool
  lib/p2p/Pool.ts
  test/integration/WebProxy.spec.ts
Labels: automated tests, bug, in progress, p2p

#544 feat(proto): ban node via gRPC
  docs/api.md
  lib/cli/commands/ban.ts
  lib/cli/commands/disconnect.ts
  lib/grpc/GrpcServer.ts
  lib/grpc/GrpcService.ts
  lib/p2p/Pool.ts
  lib/p2p/errors.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_grpc_pb.d.ts
  lib/proto/xudrpc_grpc_pb.js
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/Service.ts
  proto/xudrpc.proto
  test/integration/Service.spec.ts
  test/p2p/sanity.spec.ts
Labels: command line (CLI), grpc, in progress

#543 Refactor: add LND information to listpeers output
  docs/api.md
  lib/grpc/GrpcService.ts
  lib/p2p/Peer.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  proto/xudrpc.proto
Labels: grpc

#540 feat(grpc): add SSL to gRPC
  .env
  bin/xucli
  lib/Config.ts
  lib/Xud.ts
  lib/cli/command.ts
  lib/cli/utils.ts
  lib/grpc/GrpcServer.ts
  lib/grpc/webproxy/GrpcWebProxyServer.ts
  package-lock.json
  package.json
Labels: cryptography, grpc, in progress

#568 fix(swaps): don't calculate negative amounts
  lib/swaps/Swaps.ts
Labels: bug, in progress, swaps

#567 feat(lndclient): add nomacaroons option
  bin/xud
  lib/Config.ts
  lib/lndclient/LndClient.ts
Labels: configuration, in progress, lightning

#557 feat: add network command line argument
  bin/xud
Labels: command line (CLI), configuration, in progress

#564 refactor(lndclient): remove invoice subscription
  lib/lndclient/LndClient.ts
Labels: code quality, in progress, lightning

#546 fix(cli): fix addCurrency swapClient arg
  lib/cli/commands/addcurrency.ts
Labels: bug, command line (CLI), in progress

#559 fix(config): properly set default macaroon paths
  lib/Config.ts
  lib/Xud.ts
Labels: bug, configuration, in progress, lightning

#556 p2p.discover & p2p.detectExternalIp options #434
  bin/xud
  lib/Config.ts
  lib/p2p/Pool.ts
Labels: configuration, in progress, p2p

#541 feat(OrderBook/Swaps): placeOrder
  lib/cli/commands/orders/buy.ts
  lib/cli/commands/orders/sell.ts
  lib/cli/utils.ts
  lib/grpc/GrpcServer.ts
  lib/grpc/GrpcService.ts
  lib/orderbook/MatchingEngine.ts
  lib/orderbook/OrderBook.ts
  lib/proto/hash_resolver_grpc_pb.js
  lib/proto/lndrpc_grpc_pb.js
  lib/proto/xudrpc_grpc_pb.d.ts
  lib/proto/xudrpc_grpc_pb.js
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/Service.ts
  lib/swaps/Swaps.ts
  lib/types/matchingEngine.ts
  lib/types/orderBook.ts
  lib/types/orders.ts
  proto/xudrpc.proto
  test/integration/OrderBook.spec.ts
Labels: in progress

#563 feat(lndclient): check if chain is out of sync
  lib/BaseClient.ts
  lib/lndclient/LndClient.ts
Labels: in progress, lightning

#495 feat: check order book before accepting swap
  lib/orderbook/OrderBook.ts
  lib/p2p/packets/types/SwapResponsePacket.ts
  lib/swaps/Swaps.ts
  lib/types/enums.ts
  lib/types/orders.ts
Labels: in progress, order book, swaps

#576 refactor(db): remove seed ZRX/GNT trading pair
  lib/db/DB.ts
Labels: database, in progress

#579 feat: check if order is swappable before broadcast
  lib/orderbook/OrderBook.ts
  lib/swaps/Swaps.ts
Labels: in progress, order book, p2p, swaps

#578 feat: leave partially swapped orders in order book
  lib/orderbook/MatchingEngine.ts
  lib/orderbook/OrderBook.ts
  lib/orderbook/errors.ts
  test/unit/MatchingEngine.spec.ts
Labels: in progress, order book, swaps

#580 fix(orderbook): set localId on own order removals
  lib/orderbook/OrderBook.ts
Labels: bug, in progress, order book

#577 refactor: treat failed swaps as invalidations
  lib/orderbook/OrderBook.ts
  lib/swaps/Swaps.ts
Labels: in progress, order book, swaps

#584 Fix proto files
  docs/api.md
  lib/proto/hash_resolver_grpc_pb.js
  lib/proto/lndrpc_grpc_pb.js
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_grpc_pb.js
Labels: in progress

#581 Minor swap refactoring/renaming
  lib/orderbook/OrderBook.ts
  lib/proto/xudrpc.swagger.json
  lib/service/Service.ts
  lib/swaps/Swaps.ts
  lib/types/enums.ts
  lib/types/orders.ts
Labels: in progress

#553 refactor(lndclient): remove asObject types
  lib/lndclient/LndClient.ts
  lib/service/Service.ts
Labels: code quality, in progress, lightning, low priority

#583 Track ban
  lib/p2p/NodeList.ts
  lib/p2p/Pool.ts
  package-lock.json
Labels: in progress

#586 Fixes #539, tricky bug for removing ownOrders when there's an unreachable node
  lib/orderbook/MatchingEngine.ts
  lib/orderbook/OrderBook.ts
Labels: bug, in progress, order book, p2p

#590 refactor: make static constants readonly
  lib/Logger.ts
  lib/lndclient/LndClient.ts
  lib/orderbook/OrderBook.ts
  lib/p2p/NodeList.ts
  lib/p2p/Parser.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/p2p/packets/Packet.ts
Labels: code quality, in progress, low priority

#591 refactor(swaps): make errorReason nullable
  lib/swaps/Swaps.ts
Labels: in progress

#592 fix(p2p): consistent checks before connecting
  lib/grpc/GrpcService.ts
  lib/p2p/Pool.ts
  lib/p2p/errors.ts
Labels: bug, in progress, p2p

#597 refactor: create types file for swaps
  lib/swaps/types.ts
Labels: code quality, in progress, low priority

#598 fix(lnd): automatically retry if chain out of sync
  lib/lndclient/LndClient.ts
Labels: bug, in progress, lightning

#602 chore: skip current node build to fix travis
  .travis.yml
Labels: build, in progress

#585 P2P integration for added/removed trading pairs
  lib/Xud.ts
  lib/grpc/GrpcService.ts
  lib/orderbook/OrderBook.ts
  lib/service/Service.ts
  lib/types/orders.ts
Labels: in progress, order book, p2p

#596 docs: add comments to order types
  lib/types/orders.ts
Labels: documentation, in progress

#595 docs: improve proto comments.
  docs/api.md
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_grpc_pb.js
  proto/xudrpc.proto
Labels: in progress

#570 feat(getNodeInfo) get information about node
  bin/{
  docs/api.md
  lib/cli/commands/getnodeinfo.ts
  lib/grpc/GrpcServer.ts
  lib/grpc/GrpcService.ts
  lib/p2p/Pool.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_grpc_pb.d.ts
  lib/proto/xudrpc_grpc_pb.js
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/Service.ts
  proto/xudrpc.proto
Labels: in progress

#605 GetNodeInfo comments/minor changes
  docs/api.md
  lib/proto/xudrpc.swagger.json
  lib/service/Service.ts
  proto/xudrpc.proto
Labels: documentation, grpc, in progress

#607 fix(p2p): connect to peers with lastAddress only
  lib/p2p/Pool.ts
Labels: bug, in progress, p2p

#614 fix: addOwnOrder iteration call
  lib/orderbook/OrderBook.ts
Labels: in progress

#618 proto deprecation fix
  docs/api.md
  lib/proto/hash_resolver_grpc_pb.js
  lib/proto/lndrpc_grpc_pb.js
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_grpc_pb.js
Labels: in progress

#619 fix: logging text
  lib/orderbook/OrderBook.ts
Labels: in progress

#611 fix(swaps): correctly set taker & maker amounts
  lib/swaps/Swaps.ts
  test/unit/Swaps.spec.ts
Labels: automated tests, bug, in progress, swaps
