Repository ExchangeUnion/xud, pull requests merged in 2018-09, with the labels that each got.

#435 Make pairs & currencies upper case for cli
  lib/cli/commands/cancelorder.ts
  lib/cli/commands/channelbalance.ts
  lib/cli/commands/getorders.ts
  lib/cli/utils.ts
Labels: in progress

#439 Update winston
  lib/Logger.ts
  lib/winston.d.ts
  package-lock.json
  package.json
Labels: in progress, logging

#419 Added logPath to config
  bin/xud
  lib/Config.ts
  lib/Logger.ts
  lib/Xud.ts
  test/integration/Service.spec.ts
  test/integration/WebProxy.spec.ts
  test/p2p/sanity.spec.ts
Labels: in progress, logging

#380 Refactoring swaps
  lib/Logger.ts
  lib/Xud.ts
  lib/orderbook/MatchesProcessor.ts
  lib/orderbook/OrderBook.ts
  lib/orderbook/SwapDeals.ts
  lib/p2p/Parser.ts
  lib/p2p/Pool.ts
  lib/p2p/packets/types/DealResponsePacket.ts
  lib/p2p/packets/types/SwapResponsePacket.ts
  lib/p2p/packets/types/index.ts
  lib/service/Service.ts
  lib/swaps/Swaps.ts
Labels: in progress, swaps

#445 Fix rounding error on swap amounts
  lib/swaps/Swaps.ts
Labels: bug, in progress, swaps

#411 Make p2p sanity tests use dynamic ports
  lib/Xud.ts
  lib/p2p/Pool.ts
  test/p2p/sanity.spec.ts
Labels: automated tests, in progress, p2p

#446 hash-resolver rpc in lnd.proto
  lib/grpc/GrpcServer.ts
  lib/grpc/GrpcService.ts
  lib/proto/lndrpc_grpc_pb.d.ts
  lib/proto/lndrpc_grpc_pb.js
  lib/proto/lndrpc_pb.d.ts
  lib/proto/lndrpc_pb.js
  proto/lndrpc.proto
Labels: in progress

#392 connection retries
  lib/grpc/GrpcService.ts
  lib/p2p/NodeList.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/p2p/errors.ts
  lib/service/Service.ts
  lib/types/p2p.ts
  lib/utils/addressUtils.ts
  test/p2p/sanity.spec.ts
Labels: in progress

#429 Bind socket after connection
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  test/integration/Pool.spec.ts
Labels: in progress, p2p

#447 Remove maker order after successful swap
  lib/Xud.ts
  lib/orderbook/MatchesProcessor.ts
  lib/orderbook/OrderBook.ts
  lib/p2p/Pool.ts
  lib/p2p/packets/types/DealRequestPacket.ts
  lib/p2p/packets/types/DealResponsePacket.ts
  lib/p2p/packets/types/SwapRequestPacket.ts
  lib/p2p/packets/types/SwapResponsePacket.ts
  lib/service/Service.ts
  lib/swaps/Swaps.ts
Labels: in progress, order book, swaps

#451 Npm install
  instructions-for-devs.md
Labels: in progress

#438 Enable add/remove pairs & currencies from grpc
  docs/api.md
  lib/Xud.ts
  lib/cli/commands/addcurrency.ts
  lib/cli/commands/addpair.ts
  lib/cli/commands/listpairs.ts
  lib/cli/commands/removecurrency.ts
  lib/cli/commands/removepair.ts
  lib/db/DB.ts
  lib/db/models/Currency.ts
  lib/db/models/Pair.ts
  lib/grpc/GrpcServer.ts
  lib/grpc/GrpcService.ts
  lib/orderbook/OrderBook.ts
  lib/orderbook/OrderBookRepository.ts
  lib/orderbook/errors.ts
  lib/p2p/NodeList.ts
  lib/p2p/P2PRepository.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_grpc_pb.d.ts
  lib/proto/xudrpc_grpc_pb.js
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/Service.ts
  lib/types/db.ts
  lib/types/enums.ts
  lib/types/orders.ts
  lib/utils/utils.ts
  proto/xudrpc.proto
  test/integration/OrderBook.spec.ts
  test/integration/Service.spec.ts
Labels: grpc, in progress, order book

#396 Docker set grpc listen host
  docker/README.md
  docker/lnd/start-lnd.sh
  docker/xud/xud.conf
Labels: in progress

#412 Relax HelloPacket checks
  lib/p2p/Peer.ts
Labels: in progress, p2p

#466 Chore: fixing travis build
  .travis.yml
Labels: in progress

#452 Fix bug on failed connection
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
Labels: bug, in progress, p2p

#465 Remove executeSwap CLI and related code
  docs/api.md
  instructions-for-devs.md
  lib/cli/commands/executeswap.ts
  lib/grpc/GrpcServer.ts
  lib/grpc/GrpcService.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_grpc_pb.d.ts
  lib/proto/xudrpc_grpc_pb.js
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/Service.ts
  lib/swaps/Swaps.ts
  proto/xudrpc.proto
Labels: in progress

#436 order book refactoring
  lib/grpc/GrpcService.ts
  lib/orderbook/MatchingEngine.ts
  lib/orderbook/OrderBook.ts
  lib/service/Service.ts
  test/integration/OrderBook.spec.ts
  test/integration/Service.spec.ts
  test/unit/MatchingEngine.spec.ts
Labels: in progress, order book

#456 Docs: add contribution and git commit guidelines
  .git-commit-template.txt
  CONTRIBUTING.MD
Labels: documentation, in progress

#467 Chore: add nodejs current and lts travis builds
  .travis.yml
Labels: in progress

#459 docs: restructure readme, link to wiki
  README.md
  instructions-for-devs.md
  instructions-for-exchanges.md
Labels: documentation, in progress

#461 Feat: Switch from mysql to sqlite
  .travis.yml
  bin/xud
  lib/Config.ts
  lib/Xud.ts
  lib/db/DB.ts
  lib/orderbook/OrderBook.ts
  package-lock.json
  package.json
  test/integration/OrderBook.spec.ts
  test/integration/Pool.spec.ts
  test/integration/Service.spec.ts
  test/integration/WebProxy.spec.ts
  test/p2p/sanity.spec.ts
Labels: bug, database, in progress, order book

#449 CLI enhancements
  docs/api.md
  lib/cli/commands/cancelorder.ts
  lib/cli/commands/getorders.ts
  lib/grpc/GrpcServer.ts
  lib/grpc/GrpcService.ts
  lib/orderbook/OrderBook.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_grpc_pb.js
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/Service.ts
  proto/xudrpc.proto
  test/integration/OrderBook.spec.ts
  test/integration/Service.spec.ts
Labels: command line (CLI), grpc, in progress

#469 Automatically create sample config file
  .gitignore
  gulpfile.ts
  lib/Config.ts
  lib/utils/utils.ts
  package.json
  tasks/config/index.ts
  tasks/config/sample.ts
  tasks/db/dropTables.ts
  tasks/db/index.ts
  tasks/db/restart.ts
  tasks/db/truncate.ts
  tasks/index.ts
Labels: in progress

#468 SWAP protocol V2
  lib/grpc/GrpcService.ts
  lib/orderbook/OrderBook.ts
  lib/p2p/Parser.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/p2p/packets/PacketType.ts
  lib/p2p/packets/types/DealRequestPacket.ts
  lib/p2p/packets/types/DealResponsePacket.ts
  lib/p2p/packets/types/SwapCompletePacket.ts
  lib/p2p/packets/types/SwapErrorPacket.ts
  lib/p2p/packets/types/SwapRequestPacket.ts
  lib/p2p/packets/types/SwapResponsePacket.ts
  lib/p2p/packets/types/index.ts
  lib/service/Service.ts
  lib/swaps/Swaps.ts
  lib/types/enums.ts
Labels: in progress

#482 refactor(docker): remove mysql references
  docker/README.md
  docker/docker-compose.yml
  docker/xud/xud.conf
Labels: docker, in progress

#490 fix: remove reference to db in docker-compose.yml
  docker/docker-compose.yml
Labels: in progress

#484 feat(p2p): logging enhancements
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
Labels: in progress, logging, p2p

#485 docs: update contributing.md with links
  CONTRIBUTING.MD
Labels: documentation, in progress

#492 refactor: remove maxResults from getOrders
  docs/api.md
  lib/cli/commands/getorders.ts
  lib/orderbook/MatchingEngine.ts
  lib/orderbook/OrderBook.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/Service.ts
  proto/xudrpc.proto
  test/integration/OrderBook.spec.ts
  test/integration/Service.spec.ts
Labels: grpc, in progress, order book

#497 style(lint): add space-before-function-paren rule
  lib/raidenclient/RaidenClient.ts
  tslint.json
Labels: code quality, in progress

#493 test: prevent loading local config
  test/integration/OrderBook.spec.ts
  test/integration/Pool.spec.ts
  test/p2p/sanity.spec.ts
Labels: automated tests, in progress

#494 feat(CLI): getinfo presents LND's alias
  docs/api.md
  lib/grpc/GrpcService.ts
  lib/lndclient/LndClient.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  proto/xudrpc.proto
Labels: grpc, in progress

#499 chore: modify list of published files
  package.json
Labels: in progress

#501 feat(rpc): enable getting all channel balances
  docs/api.md
  lib/cli/commands/channelbalance.ts
  lib/grpc/GrpcService.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/Service.ts
  proto/xudrpc.proto
Labels: grpc, in progress

#502 fix(config): correctly set default paths
  lib/Config.ts
Labels: bug, configuration, in progress

#504 docs: add licenses to protos and update readme
  README.md
  proto/hash_resolver.proto
  proto/lndrpc.proto
  proto/xudrpc.proto
Labels: in progress

#503 feat(SWAPS): cltv-delta
  bin/xud
  lib/Config.ts
  lib/grpc/GrpcService.ts
  lib/lndclient/LndClient.ts
  lib/p2p/packets/types/SwapRequestPacket.ts
  lib/p2p/packets/types/SwapResponsePacket.ts
  lib/service/Service.ts
  lib/swaps/Swaps.ts
Labels: in progress, swaps

#514 fix(config): use custom config file path
  lib/Config.ts
Labels: bug, configuration, in progress

#511 style: use PascalCase for enums
  lib/BaseClient.ts
  lib/Config.ts
  lib/Logger.ts
  lib/db/DB.ts
  lib/lndclient/LndClient.ts
  lib/orderbook/MatchingEngine.ts
  lib/p2p/Parser.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/p2p/packets/Packet.ts
  lib/p2p/packets/PacketType.ts
  lib/p2p/packets/types/GetNodesPacket.ts
  lib/p2p/packets/types/GetOrdersPacket.ts
  lib/p2p/packets/types/HelloPacket.ts
  lib/p2p/packets/types/NodesPacket.ts
  lib/p2p/packets/types/OrderInvalidationPacket.ts
  lib/p2p/packets/types/OrderPacket.ts
  lib/p2p/packets/types/OrdersPacket.ts
  lib/p2p/packets/types/PingPacket.ts
  lib/p2p/packets/types/PongPacket.ts
  lib/p2p/packets/types/SwapCompletePacket.ts
  lib/p2p/packets/types/SwapErrorPacket.ts
  lib/p2p/packets/types/SwapRequestPacket.ts
  lib/p2p/packets/types/SwapResponsePacket.ts
  lib/raidenclient/RaidenClient.ts
  lib/types/enums.ts
  test/integration/OrderBook.spec.ts
  test/integration/Pool.spec.ts
  test/integration/Service.spec.ts
  test/unit/MatchingEngine.spec.ts
Labels: in progress

#510 test(orderbook): add case to partly fill & cancel
  test/integration/OrderBook.spec.ts
Labels: automated tests, in progress, order book

#517 test(p2p): get unused port
  lib/p2p/Pool.ts
  test/p2p/sanity.spec.ts
Labels: automated tests, in progress, p2p

#521 refactor(LND): exposes getInfo as public method using native objects
  lib/lndclient/LndClient.ts
Labels: in progress

#496 Storing lastAddress in node for outgoing connection for peer
  lib/db/models/Node.ts
  lib/p2p/NodeList.ts
  lib/p2p/Pool.ts
  lib/types/db.ts
  lib/types/p2p.ts
  lib/utils/addressUtils.ts
Labels: in progress, p2p

#515 feat(SWAPS): cltv-delta Part 2
  lib/lndclient/LndClient.ts
  lib/p2p/packets/types/SwapErrorPacket.ts
  lib/swaps/Swaps.ts
Labels: in progress

#512 Prevent connecting to a node if we're already attempting a pending connection
  lib/p2p/Pool.ts
Labels: p2p

#519 style(config): use lower case for all config vars
  bin/xud
  lib/Config.ts
  lib/Xud.ts
  test/integration/Service.spec.ts
  test/integration/WebProxy.spec.ts
  test/p2p/sanity.spec.ts
Labels: configuration, in progress

#524 test: use in-memory db for web proxy tests
  test/integration/WebProxy.spec.ts
Labels: automated tests, in progress

#525 refactor: use positive quantity for buys & sells
  docs/api.md
  lib/cli/utils.ts
  lib/grpc/GrpcService.ts
  lib/orderbook/MatchingEngine.ts
  lib/orderbook/OrderBook.ts
  lib/proto/hash_resolver_grpc_pb.js
  lib/proto/lndrpc_grpc_pb.js
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_grpc_pb.js
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/Service.ts
  lib/swaps/Swaps.ts
  lib/types/enums.ts
  lib/types/orders.ts
  proto/xudrpc.proto
  test/integration/OrderBook.spec.ts
  test/integration/Service.spec.ts
  test/unit/MatchingEngine.spec.ts
Labels: grpc, in progress, order book

#522 fix: don't send order invalidation to taker
  lib/orderbook/OrderBook.ts
  lib/p2p/Pool.ts
  lib/swaps/Swaps.ts
Labels: bug, in progress, order book

#523 test: use dynamic port for web proxy tests
  test/integration/WebProxy.spec.ts
  test/p2p/sanity.spec.ts
  test/utils.ts
Labels: automated tests, in progress

#500 feat(rpc): add new order events rpc subscriptions
  docs/api.md
  lib/cli/commands/subscribeorders.ts
  lib/cli/commands/subscribepeerorders.ts
  lib/cli/commands/subscribeswaps.ts
  lib/grpc/GrpcServer.ts
  lib/grpc/GrpcService.ts
  lib/orderbook/MatchingEngine.ts
  lib/orderbook/OrderBook.ts
  lib/p2p/Pool.ts
  lib/p2p/packets/types/OrderInvalidationPacket.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_grpc_pb.d.ts
  lib/proto/xudrpc_grpc_pb.js
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/Service.ts
  lib/swaps/Swaps.ts
  lib/types/orders.ts
  proto/xudrpc.proto
  test/unit/MatchingEngine.spec.ts
Labels: grpc, in progress

#470 feat(p2p): add reputation events
  lib/db/DB.ts
  lib/db/models/ReputationEvent.ts
  lib/p2p/NodeList.ts
  lib/p2p/P2PRepository.ts
  lib/p2p/Pool.ts
  lib/types/db.ts
  lib/types/enums.ts
  test/integration/OrderBook.spec.ts
  test/p2p/sanity.spec.ts
Labels: database, in progress, p2p

#489 chore: generate sample config on new version
  .gitattributes
  .gitignore
  package.json
  sample-xud.conf
  tasks/config/sample.ts
Labels: in progress
