Repository ExchangeUnion/xud, pull requests merged in 2018-08, with the labels that each got.

#234 placeOrder gRPC error handling
  lib/cli/command.ts
  lib/constants/errorCodesPrefix.ts
  lib/grpc/GrpcService.ts
  lib/lndclient/errors.ts
  lib/orderbook/OrderBook.ts
  lib/orderbook/errors.ts
  lib/p2p/errors.ts
  lib/raidenclient/RaidenClient.ts
  lib/raidenclient/errors.ts
  lib/service/Service.ts
  lib/service/errors.ts
Labels: in progress

#210 Allow empty packets, packet ids, type in header
  lib/orderbook/OrderBook.ts
  lib/p2p/HostList.ts
  lib/p2p/Parser.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/p2p/packets/Packet.ts
  lib/p2p/packets/PacketType.ts
  lib/p2p/packets/index.ts
  lib/p2p/packets/packetUtils.ts
  lib/p2p/packets/types/GetHostsPacket.ts
  lib/p2p/packets/types/GetOrdersPacket.ts
  lib/p2p/packets/types/HostsPacket.ts
  lib/p2p/packets/types/OrdersPacket.ts
  lib/p2p/packets/types/PingPacket.ts
  lib/p2p/packets/types/PongPacket.ts
  lib/utils/utils.ts
  package-lock.json
  package.json
Labels: in progress

#245 Market order docs
  lib/cli/commands/placeorder.ts
  lib/service/Service.ts
Labels: in progress

#259 Handle duplicate placeorder localId
  lib/grpc/GrpcService.ts
  lib/orderbook/OrderBook.ts
  lib/orderbook/errors.ts
Labels: in progress

#255 Fix socket error & close handling
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/service/Service.ts
Labels: in progress

#263 Fix bug causing host uniqueness violation
  lib/db/models/Host.ts
  lib/p2p/HostList.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/p2p/packets/types/HostsPacket.ts
Labels: in progress

#268 Handle already connected grpc error
  lib/grpc/GrpcService.ts
Labels: in progress

#256 Replace hostId with peerId on orders
  lib/orderbook/MatchingEngine.ts
  lib/orderbook/OrderBook.ts
  lib/p2p/Pool.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/types/db.ts
  lib/types/orders.ts
  proto/xudrpc.proto
  test/unit/MatchingEngine.spec.ts
Labels: in progress

#278 non-internal match order update
  lib/orderbook/OrderBook.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/types/orders.ts
  proto/xudrpc.proto
Labels: in progress

#248 Readme v2
  README.md
  instructions-for-devs.md
  instructions-for-exchanges.md
Labels: in progress

#244 P2P Seeding
  gulpfile.ts
  lib/db/DB.ts
  lib/p2p/Host.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  tasks/db/init.ts
Labels: in progress

#279 Change version from 1.0.0-alpha.1 to 1.0.0-prealpha.1
  package-lock.json
  package.json
Labels: in progress

#287 add 'v' to tag
  instructions-for-devs.md
Labels: in progress, mid priority

#266 Order invalidation implementation
  lib/orderbook/MatchingEngine.ts
  lib/orderbook/OrderBook.ts
  lib/p2p/Pool.ts
  lib/service/Service.ts
  test/integration/OrderBook.spec.ts
  test/unit/MatchingEngine.spec.ts
Labels: in progress

#295 Initialize pool after orderbook
  lib/Xud.ts
Labels: in progress

#300 Remove extraneous hostId missing logging
  lib/p2p/Pool.ts
Labels: in progress

#264 ListPeers gRPC call
  lib/cli/commands/listpeers.ts
  lib/grpc/GrpcServer.ts
  lib/grpc/GrpcService.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_grpc_pb.d.ts
  lib/proto/xudrpc_grpc_pb.js
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/Service.ts
  proto/xudrpc.proto
Labels: in progress

#301 Remove extraneous p2p logging & closes
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
Labels: in progress, p2p

#247 Member-ordering lint rule
  lib/Logger.ts
  lib/Xud.ts
  lib/p2p/Peer.ts
  tslint.json
Labels: code quality, in progress

#293 Improved getOrders
  lib/cli/commands/getorders.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/Service.ts
  proto/xudrpc.proto
Labels: in progress

#299 Enforce noImplicitAny rule
  lib/Config.ts
  lib/Logger.ts
  lib/Xud.ts
  lib/db/models/Pair.ts
  lib/grpc/GrpcService.ts
  lib/grpc/webproxy/GrpcExpressMiddleware.ts
  lib/grpc/webproxy/GrpcWebProxyServer.ts
  lib/lndclient/LndClient.ts
  lib/nodekey/NodeKey.ts
  lib/orderbook/MatchesProcessor.ts
  lib/orderbook/MatchingEngine.ts
  lib/orderbook/OrderBook.ts
  lib/orderbook/errors.ts
  lib/p2p/Parser.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/raidenclient/RaidenClient.ts
  lib/service/Service.ts
  lib/types/orders.ts
  lib/utils/utils.ts
  lib/winston.d.ts
  package-lock.json
  package.json
  test/integration/OrderBook.spec.ts
  tsconfig.json
Labels: code quality, in progress

#307 connection timeout handling
  lib/p2p/Peer.ts
Labels: in progress

#281 Peer disconnect log message
  lib/p2p/Host.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
Labels: in progress

#328 db:init task fix
  package-lock.json
  package.json
  tasks/db/init.ts
Labels: in progress

#236 Preparation for Raiden swaps
  lib/BaseClient.ts
  lib/Xud.ts
  lib/cli/commands/executeswap.ts
  lib/db/models/Currency.ts
  lib/grpc/GrpcService.ts
  lib/orderbook/MatchesProcessor.ts
  lib/orderbook/OrderBook.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/raidenclient/README.md
  lib/raidenclient/RaidenClient.ts
  lib/service/Service.ts
  lib/types/db.ts
  proto/xudrpc.proto
Labels: in progress

#323 Add comments, rename variables, minor refactoring
  lib/BaseClient.ts
  lib/Xud.ts
  lib/cli/command.ts
  lib/db/DB.ts
  lib/grpc/GrpcServer.ts
  lib/grpc/webproxy/GrpcWebProxyServer.ts
  lib/lndclient/LndClient.ts
  lib/nodekey/NodeKey.ts
  lib/orderbook/MatchingEngine.ts
  lib/orderbook/OrderBook.ts
  lib/p2p/Peer.ts
  lib/p2p/PeerList.ts
  lib/p2p/Pool.ts
  lib/p2p/SocketAddress.ts
  lib/p2p/packets/Packet.ts
  lib/raidenclient/RaidenClient.ts
  lib/service/Service.ts
  lib/types/matchingEngine.ts
  lib/utils/utils.ts
  test/integration/OrderBook.spec.ts
  test/unit/MatchingEngine.spec.ts
Labels: code quality, documentation, in progress

#334 Update instructions-for-devs.md
  instructions-for-devs.md
Labels: in progress

#132 P2P sanity tests #96
  lib/BaseClient.ts
  lib/Config.ts
  lib/Logger.ts
  lib/Xud.ts
  lib/db/DB.ts
  lib/grpc/GrpcServer.ts
  lib/grpc/GrpcService.ts
  lib/grpc/webproxy/GrpcWebProxyServer.ts
  lib/lndclient/LndClient.ts
  lib/nodekey/NodeKey.ts
  lib/orderbook/MatchesProcessor.ts
  lib/orderbook/MatchingEngine.ts
  lib/orderbook/OrderBook.ts
  lib/orderbook/OrderBookRepository.ts
  lib/p2p/P2PRepository.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/p2p/errors.ts
  lib/raidenclient/RaidenClient.ts
  lib/service/Service.ts
  package-lock.json
  package.json
  tasks/db/dropTables.ts
  tasks/db/init.ts
  tasks/db/truncate.ts
  test/integration/OrderBook.spec.ts
  test/p2p/sanity.spec.ts
  test/unit/MatchingEngine.spec.ts
Labels: in progress

#333 Set version on handshake
  lib/Xud.ts
  lib/service/Service.ts
Labels: in progress, p2p

#337 drop duplicated peer orders
  lib/orderbook/OrderBook.ts
Labels: in progress

#338 protoc enhancements - macos/linux
  lib/proto/annotations_pb.d.ts
  lib/proto/google/api/http_pb.d.ts
  lib/proto/google/protobuf/descriptor_pb.d.ts
  lib/proto/lndrpc_pb.d.ts
  lib/proto/xudrpc_pb.d.ts
  package-lock.json
  package.json
  proto/README.md
Labels: in progress

#347 Fix shutdown procedure
  lib/Xud.ts
  lib/lndclient/LndClient.ts
Labels: bug, in progress

#343 Separated placeorder command
  bin/xucli
  lib/cli/commands/orders/limitorder.ts
  lib/cli/commands/orders/marketorder.ts
Labels: in progress

#329 add node_modules caching
  .travis.yml
Labels: in progress

#315 Peer/Host restructuring
  bin/xud
  instructions-for-devs.md
  lib/Config.ts
  lib/Xud.ts
  lib/cli/commands/connect.ts
  lib/cli/commands/disconnect.ts
  lib/db/DB.ts
  lib/db/models/BannedHost.ts
  lib/db/models/Host.ts
  lib/db/models/Node.ts
  lib/grpc/GrpcService.ts
  lib/grpc/webproxy/GrpcWebProxyServer.ts
  lib/nodekey/NodeKey.ts
  lib/orderbook/MatchingEngine.ts
  lib/orderbook/OrderBook.ts
  lib/p2p/Host.ts
  lib/p2p/HostList.ts
  lib/p2p/NodeList.ts
  lib/p2p/P2PRepository.ts
  lib/p2p/Parser.ts
  lib/p2p/Peer.ts
  lib/p2p/PeerList.ts
  lib/p2p/Pool.ts
  lib/p2p/SocketAddress.ts
  lib/p2p/errors.ts
  lib/p2p/packets/PacketType.ts
  lib/p2p/packets/types/GetNodesPacket.ts
  lib/p2p/packets/types/NodesPacket.ts
  lib/p2p/packets/types/index.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_grpc_pb.js
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/Service.ts
  lib/types/db.ts
  lib/types/index.ts
  lib/types/orders.ts
  lib/types/p2p.ts
  lib/utils/addressUtils.ts
  package-lock.json
  package.json
  proto/xudrpc.proto
  test/integration/OrderBook.spec.ts
  test/p2p/sanity.spec.ts
  test/unit/MatchingEngine.spec.ts
Labels: in progress, p2p

#332 Add tslint rules
  lib/Config.ts
  lib/Logger.ts
  lib/Xud.ts
  lib/grpc/GrpcService.ts
  lib/lndclient/LndClient.ts
  lib/orderbook/OrderBook.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/p2p/packets/Packet.ts
  lib/raidenclient/RaidenClient.ts
  lib/service/Service.ts
  lib/utils/utils.ts
  tslint-alt.json
  tslint.json
Labels: code quality, in progress

#350 Switch to upstream fastpriorityqueue
  lib/orderbook/MatchingEngine.ts
  package-lock.json
  package.json
Labels: in progress

#330 Wire protocol
  lib/p2p/Parser.ts
  lib/p2p/Peer.ts
  lib/p2p/packets/Packet.ts
  test/unit/Parser.spec.ts
Labels: in progress

#355 Update node addresses on handshake
  lib/p2p/NodeList.ts
  lib/p2p/P2PRepository.ts
  lib/p2p/Pool.ts
  test/integration/Pool.spec.ts
  test/p2p/sanity.spec.ts
Labels: in progress, p2p

#317 Discover node's external IP
  lib/p2p/Pool.ts
  lib/p2p/errors.ts
  lib/utils/utils.ts
Labels: in progress

#360 Add tslint whitespace rules
  test/p2p/sanity.spec.ts
  tslint.json
Labels: code quality, in progress

#363 Add aliases for db name and webproxy port
  bin/xud
Labels: command line, in progress

#364 Fix custom folder config
  bin/xud
  lib/Config.ts
  lib/Xud.ts
  test/integration/Pool.spec.ts
  test/integration/WebProxy.spec.ts
  test/p2p/sanity.spec.ts
Labels: bug, configuration, in progress

#367 Configure package for distribution
  package-lock.json
  package.json
Labels: code quality, in progress

#359 Lnd swap packets
  docs/api.md
  lib/Xud.ts
  lib/cli/commands/executeswap.ts
  lib/orderbook/SwapDeals.ts
  lib/p2p/Parser.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/p2p/packets/PacketType.ts
  lib/p2p/packets/types/DealRequestPacket.ts
  lib/p2p/packets/types/DealResponsePacket.ts
  lib/p2p/packets/types/SwapRequestPacket.ts
  lib/p2p/packets/types/SwapResponsePacket.ts
  lib/p2p/packets/types/index.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/raidenclient/RaidenClient.ts
  lib/service/Service.ts
  lib/types/enums.ts
  proto/xudrpc.proto
Labels: in progress, swaps

#371 LND swap protocol
  test/integration/Pool.spec.ts
Labels: in progress

#344 Refactor gRPC
  lib/grpc/GrpcServer.ts
  lib/grpc/GrpcService.ts
  lib/lndclient/LndClient.ts
  lib/raidenclient/RaidenClient.ts
  lib/service/Service.ts
Labels: grpc, in progress

#358 Refactor placeOrder
  docs/api.md
  lib/cli/commands/orders/limitorder.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/Service.ts
  proto/xudrpc.proto
Labels: grpc, in progress

#357 Service tests
  docs/api.md
  lib/Xud.ts
  lib/grpc/GrpcService.ts
  lib/p2p/Pool.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_grpc_pb.js
  lib/service/Service.ts
  proto/xudrpc.proto
  test/integration/Pool.spec.ts
  test/integration/Service.spec.ts
  test/integration/WebProxy.spec.ts
  test/p2p/sanity.spec.ts
Labels: automated tests, bug, in progress

#374 Update tslint-config-airbnb
  lib/p2p/packets/Packet.ts
  package-lock.json
  package.json
  tslint.json
Labels: code quality, in progress

#375 Fixed addresses bug
  lib/p2p/Pool.ts
Labels: bug, in progress

#372 Switched to LND URI format
  docs/api.md
  lib/cli/commands/connect.ts
  lib/grpc/GrpcService.ts
  lib/p2p/Pool.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/Service.ts
  lib/utils/utils.ts
  proto/xudrpc.proto
  test/p2p/sanity.spec.ts
Labels: in progress

#382 LND swap resolver support
  lib/grpc/GrpcServer.ts
  lib/grpc/GrpcService.ts
  lib/orderbook/SwapDeals.ts
  lib/proto/swap_resolver_grpc_pb.d.ts
  lib/proto/swap_resolver_grpc_pb.js
  lib/proto/swap_resolver_pb.d.ts
  lib/proto/swap_resolver_pb.js
  lib/service/Service.ts
  package.json
  proto/swap_resolver.proto
Labels: in progress

#368 Resolve peer-pool circular import
  lib/Xud.ts
  lib/orderbook/SwapDeals.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/p2p/packets/types/DealRequestPacket.ts
  lib/p2p/packets/types/SwapResponsePacket.ts
  lib/service/Service.ts
  lib/types/enums.ts
  test/integration/Pool.spec.ts
Labels: in progress, swaps

#376 parser unit tests
  test/unit/Parser.spec.ts
Labels: in progress

#361 Add tslint circular import rule
  lib/types/p2p.ts
  package-lock.json
  package.json
  tslint.json
Labels: code quality, in progress

#378 Remove Docker image build on Travis CI
  .travis.yml
Labels: in progress

#379 p2p sanity config fix
  lib/Config.ts
  test/p2p/sanity.spec.ts
Labels: in progress

#385 Removed remainingOrder from market orders
  lib/orderbook/OrderBook.ts
  test/integration/OrderBook.spec.ts
Labels: in progress

#389 Don't wait for outgoing connections on start
  lib/p2p/Pool.ts
Labels: in progress, p2p

#381 Make lint script autofix errors
  .travis.yml
  package.json
  tslint-alt.json
Labels: code quality, in progress

#388 Swap orderbook integration
  lib/orderbook/MatchesProcessor.ts
  lib/orderbook/OrderBook.ts
  lib/orderbook/SwapDeals.ts
  lib/p2p/Pool.ts
  lib/p2p/packets/types/DealRequestPacket.ts
  lib/p2p/packets/types/OrderPacket.ts
  lib/types/orders.ts
  test/unit/MatchingEngine.spec.ts
Labels: in progress, order book, swaps

#395 LND swap resolver support
  lib/Xud.ts
  lib/grpc/GrpcService.ts
  lib/lndclient/LndClient.ts
  lib/p2p/Pool.ts
  lib/service/Service.ts
Labels: in progress, swaps

#390 Configurable log level
  bin/xud
  lib/Config.ts
  lib/Logger.ts
  lib/Xud.ts
  lib/db/DB.ts
  lib/orderbook/OrderBookRepository.ts
  lib/p2p/P2PRepository.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  package-lock.json
  package.json
  test/integration/OrderBook.spec.ts
  test/integration/Pool.spec.ts
  test/integration/Service.spec.ts
  test/integration/WebProxy.spec.ts
  test/p2p/sanity.spec.ts
  test/unit/MatchingEngine.spec.ts
Labels: in progress

#399 Order match swap execution fixes
  lib/grpc/GrpcService.ts
  lib/orderbook/MatchesProcessor.ts
  lib/orderbook/SwapDeals.ts
  lib/p2p/Pool.ts
  lib/service/Service.ts
Labels: in progress, swaps

#397 Fix BTC/LTC ticker to LTC/BTC
  instructions-for-devs.md
  lib/db/DB.ts
  test/integration/OrderBook.spec.ts
  test/integration/Service.spec.ts
  test/unit/MatchingEngine.spec.ts
  test/unit/Parser.spec.ts
Labels: in progress

#393 Share only connected peers on GET_NODES
  lib/p2p/NodeList.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
Labels: in progress, p2p

#377 Peer disconnect log message format
  lib/p2p/Pool.ts
Labels: in progress

#406 Fix rounding error on swap amounts
  lib/orderbook/MatchesProcessor.ts
Labels: bug, in progress, swaps

#420 Npm run compile
  instructions-for-devs.md
  package-lock.json
  package.json
Labels: in progress

#400 Verify reachability of advertised addresses
  lib/Logger.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  test/p2p/sanity.spec.ts
Labels: in progress

#427 Fix cancelorder invalid pair false positive
  lib/orderbook/OrderBook.ts
Labels: bug, in progress

#414 Buy & sell xucli commands for placing orders
  lib/cli/commands/orders/buy.ts
  lib/cli/commands/orders/limitorder.ts
  lib/cli/commands/orders/marketorder.ts
  lib/cli/commands/orders/sell.ts
  lib/cli/utils.ts
  lib/orderbook/OrderBook.ts
  lib/p2p/Peer.ts
Labels: command line (CLI), in progress, order book
