Repository ExchangeUnion/xud, pull requests merged in 2019-06, with the labels that each got.

#976 fix: swap client initialization
  lib/Xud.ts
  lib/orderbook/OrderBook.ts
  lib/p2p/Pool.ts
  lib/p2p/types.ts
  lib/raidenclient/RaidenClient.ts
  lib/swaps/SwapClientManager.ts
  lib/swaps/Swaps.ts
  lib/swaps/types.ts
  test/integration/OrderBook.spec.ts
  test/integration/Pool.spec.ts
  test/jest/Orderbook.spec.ts
  test/jest/SwapClientManager.spec.ts
  test/simulation/tests.go
Labels: bug, swaps

#1003 refactor: mock swaps module for tests
  lib/orderbook/OrderBook.ts
  test/integration/OrderBook.spec.ts
Labels: automated tests, code quality

#1005 refactor(orderbook): pass object to constructor
  lib/Xud.ts
  lib/orderbook/OrderBook.ts
  test/integration/OrderBook.spec.ts
  test/jest/Orderbook.spec.ts
Labels: code quality, order book

#1008 fix: deprecation warnings from crypto dependency
  lib/p2p/Framer.ts
  lib/p2p/Peer.ts
  lib/p2p/packets/Packet.ts
  lib/utils/utils.ts
  test/crypto/handshake.ts
  test/unit/Parser.spec.ts
Labels: code quality

#1007 Master key refactor
  lib/Xud.ts
  lib/db/DB.ts
  lib/lndclient/LndClient.ts
  lib/lndclient/types.ts
  lib/p2p/Pool.ts
  lib/raidenclient/RaidenClient.ts
  lib/swaps/SwapClient.ts
  lib/swaps/SwapClientManager.ts
  lib/swaps/Swaps.ts
  test/integration/Pool.spec.ts
  test/integration/Service.spec.ts
  test/jest/Orderbook.spec.ts
  test/jest/SwapClientManager.spec.ts
  test/p2p/networks.spec.ts
  test/p2p/sanity.spec.ts
  test/simulation/xudtest/node.go
  test/unit/DB.spec.ts
Labels: automated tests, code quality

#1023 fix(cli): quantity rounding
  lib/cli/commands/executeswap.ts
  lib/cli/commands/listorders.ts
  lib/cli/commands/removeorder.ts
  lib/cli/utils.ts
  test/unit/Command.spec.ts
Labels: bug, command line (CLI)

#973 feat(seedutil): generate eth keystore from aezeed mnemonic
  .gitignore
  .travis.yml
  jest.config.js
  package.json
  seedutil/README.md
  seedutil/SeedUtil.spec.ts
  seedutil/go.mod
  seedutil/go.sum
  seedutil/main.go
Labels: raiden

#1024 fix: blockheight prop of `undefined` in GetInfo
  lib/grpc/GrpcService.ts
  lib/lndclient/types.ts
  lib/service/Service.ts
  lib/swaps/SwapClientManager.ts
Labels: bug, lightning

#1006 feat: xud master password
  bin/xud
  docs/api.md
  lib/Config.ts
  lib/Xud.ts
  lib/cli/command.ts
  lib/cli/commands/create.ts
  lib/cli/commands/unlock.ts
  lib/grpc/GrpcInitService.ts
  lib/grpc/GrpcServer.ts
  lib/http/HttpServer.ts
  lib/lndclient/LndClient.ts
  lib/nodekey/NodeKey.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_grpc_pb.d.ts
  lib/proto/xudrpc_grpc_pb.js
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/InitService.ts
  lib/service/Service.ts
  lib/service/errors.ts
  lib/swaps/SwapClient.ts
  lib/swaps/SwapClientManager.ts
  package-lock.json
  package.json
  proto/xudrpc.proto
  test/crypto/handshake.ts
  test/integration/Pool.spec.ts
  test/p2p/sanity.spec.ts
  test/simulation/tests.go
  test/unit/NodeKey.spec.ts
Labels: lightning, security

#960 feat(cli): add orderbook command
  lib/cli/command.ts
  lib/cli/commands/orderbook.ts
  test/unit/Command.orderbook.spec.ts
Labels: command line (CLI), order book

#1045 fix(lndclient): unknown service lnrpc.Lightning
  bin/xud
  lib/Xud.ts
  lib/lndclient/LndClient.ts
  lib/lndclient/errors.ts
  lib/raidenclient/RaidenClient.ts
  lib/swaps/SwapClient.ts
  lib/swaps/SwapClientManager.ts
  test/jest/SwapClientManager.spec.ts
Labels: bug, lightning

#1042 chore: reenable v12 current node build
  .travis.yml
  package-lock.json
  package.json
Labels: build

#1046 feat(logger): optional subcontext
  lib/Logger.ts
  lib/lndclient/types.ts
  lib/swaps/SwapClientManager.ts
  test/jest/SwapClientManager.spec.ts
Labels: logging

#1060 build: cache seedutil go modules
  .travis.yml
Labels: build

#1064 refactor(raiden): update channel methods
  lib/raidenclient/RaidenClient.ts
  lib/raidenclient/types.ts
Labels: raiden
