Repository ExchangeUnion/xud, pull requests merged in 2019-11, with the labels that each got.

#1312 chore: support node.js lts only into readme
  README.md
Labels: documentation

#1032 feat: add backup daemon
  bin/xud-backup
  lib/Logger.ts
  lib/backup/Backup.ts
  lib/lndclient/LndClient.ts
Labels: P1

#1316 chore: update grpc dependency for node v13
  npm-shrinkwrap.json
  package.json
Labels: build

#1142 test(simulation): retry reading tls cert
  README.md
  test/simulation/xudtest/node.go
Labels: P1, review required

#1318 test: pool suite cleanup
  test/jest/Pool.spec.ts
Labels: automated tests, p2p

#1317 fix(rpc/cli): separate inactive channel balance in getbalance
  docs/api.md
  lib/cli/commands/getbalance.ts
  lib/grpc/GrpcService.ts
  lib/lndclient/LndClient.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/raidenclient/RaidenClient.ts
  lib/service/Service.ts
  lib/swaps/SwapClient.ts
  proto/xudrpc.proto
  test/jest/Service.spec.ts
  test/jest/__snapshots__/Service.spec.ts.snap
Labels: grpc

#1320 fix(p2p): handshake race conditions
  lib/p2p/NodeList.ts
  lib/p2p/P2PRepository.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  test/integration/Pool.spec.ts
  test/jest/Pool.spec.ts
  test/unit/DB.spec.ts
Labels: automated tests, code quality, p2p

#1326 chore: compile:dev npm script
  package.json
  tsconfig.json
Labels: build

#1325 refactor(db): addOrderIfNotExists
  lib/orderbook/OrderBookRepository.ts
  test/unit/DB.spec.ts
Labels: code quality, database

#1195 test: add weth-btc simulation test
  .gitignore
  .travis.yml
  lib/raidenclient/RaidenClient.ts
  package.json
  test/jest/RaidenClient.spec.ts
  test/simulation/.env
  test/simulation/README.md
  test/simulation/actions.go
  test/simulation/address-to-eip55.sh
  test/simulation/attach-geth.sh
  test/simulation/clean.sh
  test/simulation/cleanup-processes.sh
  test/simulation/config.go
  test/simulation/create-ethereum-account.sh
  test/simulation/create-geth-genesis.sh
  test/simulation/create-raiden-config.sh
  test/simulation/deploy-contracts.sh
  test/simulation/generate-ethereum-blocks.sh
  test/simulation/get-alice-channels.sh
  test/simulation/get-bob-channels.sh
  test/simulation/go.mod
  test/simulation/go.sum
  test/simulation/install-ethereum-utils.sh
  test/simulation/install-ethereum.sh
  test/simulation/install-geth.sh
  test/simulation/install-lnd.sh
  test/simulation/install-raiden-contracts.sh
  test/simulation/install-raiden.sh
  test/simulation/install-solc.sh
  test/simulation/install.sh
  test/simulation/logs.sh
  test/simulation/raiden-config-template.toml
  test/simulation/start-autominer.sh
  test/simulation/start-geth.sh
  test/simulation/start-raiden-alice.sh
  test/simulation/start-raiden-bob.sh
  test/simulation/start-raiden.sh
  test/simulation/tests-integration.go
  test/simulation/utils/create-account.js
  test/simulation/utils/ethereum/eip55.py
  test/simulation/utils/ethereum/geth-autominer.py
  test/simulation/utils/ethereum/requirements.txt
  test/simulation/utils/genesis.json
  test/simulation/xud_test.go
  test/simulation/xudtest/node.go
Labels: P1

#1336 refactor(p2p): check socket on send
  lib/p2p/Peer.ts
Labels: code quality, p2p

#1285 feat: add xud status
  lib/cli/commands/getinfo.ts
Labels: enhancement

#1335 test(simulation): extend context wait time
  test/simulation/xudtest/node.go
Labels: automated tests, build

#1333 PlaceOrder to support replacing a previous order
  docs/api.md
  lib/cli/commands/buy.ts
  lib/cli/commands/sell.ts
  lib/cli/placeorder.ts
  lib/orderbook/OrderBook.ts
  lib/orderbook/errors.ts
  lib/proto/annotations_grpc_pb.js
  lib/proto/xudp2p_grpc_pb.js
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/Service.ts
  proto/xudrpc.proto
Labels: grpc, order book
