Repository ExchangeUnion/xud, pull requests merged in 2019-04, with the labels that each got.

#857 feat(swaps): get peer identifier for swaps
  docs/api.md
  lib/BaseClient.ts
  lib/cli/commands/addcurrency.ts
  lib/constants/enums.ts
  lib/db/DB.ts
  lib/grpc/GrpcService.ts
  lib/lndclient/LndClient.ts
  lib/orderbook/types.ts
  lib/p2p/Peer.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/raidenclient/RaidenClient.ts
  lib/service/Service.ts
  lib/swaps/Swaps.ts
  proto/xudrpc.proto
  test/integration/OrderBook.spec.ts
  test/integration/Service.spec.ts
  test/integration/Swaps.spec.ts
  test/unit/DB.spec.ts
Labels: grpc, in progress, raiden, swaps

#860 feat(swaps): use configurable amount of subunits per currency
  lib/swaps/Swaps.ts
  test/unit/Swaps.spec.ts
Labels: in progress, swaps

#859 feat(rpc): add SubscribeSwapFailures rpc call
  docs/api.md
  lib/cli/commands/streamorders.ts
  lib/grpc/GrpcServer.ts
  lib/grpc/GrpcService.ts
  lib/proto/annotations_pb.d.ts
  lib/proto/google/api/http_pb.d.ts
  lib/proto/google/protobuf/descriptor_pb.d.ts
  lib/proto/hash_resolver_grpc_pb.d.ts
  lib/proto/hash_resolver_pb.d.ts
  lib/proto/lndrpc_grpc_pb.d.ts
  lib/proto/lndrpc_pb.d.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_grpc_pb.d.ts
  lib/proto/xudrpc_grpc_pb.js
  lib/proto/xudrpc_pb.d.ts
  lib/service/Service.ts
  package-lock.json
  package.json
  proto/xudrpc.proto
Labels: grpc, in progress, swaps

#848 test(p2p): add connect test if we are banned
  test/p2p/sanity.spec.ts
Labels: automated tests, in progress, p2p

#858 feat(raiden): detect raiden address change
  lib/BaseClient.ts
  lib/Xud.ts
  lib/lndclient/LndClient.ts
  lib/p2p/Pool.ts
  lib/raidenclient/RaidenClient.ts
Labels: in progress, raiden

#829 chore(devtools): add dev:watch:inspect script
  package.json
Labels: enhancement, in progress

#867 style: clean up imports
  lib/db/types.ts
  lib/orderbook/types.ts
  lib/p2p/Pool.ts
  lib/p2p/packets/types/SessionAckPacket.ts
  lib/service/Service.ts
  lib/swaps/Swaps.ts
Labels: code quality, in progress

#868 refactor(orderbook): throw error on non-swap fail
  lib/lndclient/LndClient.ts
  lib/orderbook/OrderBook.ts
Labels: error handling, in progress, logging

#852 test: xud-simulation migration
  .gitignore
  .travis.yml
  lib/swaps/Swaps.ts
  package.json
  test/simulation/README.md
  test/simulation/actions.go
  test/simulation/clean.sh
  test/simulation/config.go
  test/simulation/go.mod
  test/simulation/go.sum
  test/simulation/install.sh
  test/simulation/lntest/COPYING.md
  test/simulation/lntest/doc.go
  test/simulation/lntest/harness.go
  test/simulation/lntest/hash.go
  test/simulation/lntest/node.go
  test/simulation/xud_test.go
  test/simulation/xudrpc/README.md
  test/simulation/xudrpc/annotations.proto
  test/simulation/xudrpc/gen_protos.sh
  test/simulation/xudrpc/google/api/http.proto
  test/simulation/xudrpc/google/protobuf/descriptor.proto
  test/simulation/xudrpc/xudrpc.pb.go
  test/simulation/xudrpc/xudrpc.proto
  test/simulation/xudtest/doc.go
  test/simulation/xudtest/harness.go
  test/simulation/xudtest/node.go
Labels: automated tests, in progress

#862 feat(p2p): verify response packet type
  lib/p2p/Peer.ts
  lib/p2p/packets/Packet.ts
  lib/p2p/packets/types/DisconnectingPacket.ts
  lib/p2p/packets/types/GetNodesPacket.ts
  lib/p2p/packets/types/GetOrdersPacket.ts
  lib/p2p/packets/types/NodeStateUpdatePacket.ts
  lib/p2p/packets/types/NodesPacket.ts
  lib/p2p/packets/types/OrderInvalidationPacket.ts
  lib/p2p/packets/types/OrderPacket.ts
  lib/p2p/packets/types/OrdersPacket.ts
  lib/p2p/packets/types/PingPacket.ts
  lib/p2p/packets/types/PongPacket.ts
  lib/p2p/packets/types/SessionAckPacket.ts
  lib/p2p/packets/types/SessionInitPacket.ts
  lib/p2p/packets/types/SwapAcceptedPacket.ts
  lib/p2p/packets/types/SwapCompletePacket.ts
  lib/p2p/packets/types/SwapFailedPacket.ts
  lib/p2p/packets/types/SwapRequestPacket.ts
Labels: in progress

#861 fix(raiden): add getRoutes and getHeight compatibility
  lib/BaseClient.ts
  lib/lndclient/LndClient.ts
  lib/raidenclient/RaidenClient.ts
  lib/swaps/types.ts
Labels: in progress, raiden

#827 XU networks support
  bin/xud
  lib/Config.ts
  lib/Xud.ts
  lib/constants/enums.ts
  lib/db/DB.ts
  lib/p2p/Framer.ts
  lib/p2p/Network.ts
  lib/p2p/NodeList.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/p2p/errors.ts
  lib/p2p/seeds/index.ts
  lib/p2p/seeds/mainnet.ts
  lib/p2p/seeds/simnet.ts
  lib/p2p/seeds/testnet.ts
  lib/p2p/types.ts
  test/integration/Pool.spec.ts
  test/integration/Swaps.spec.ts
  test/p2p/networks.spec.ts
  test/p2p/sanity.spec.ts
  test/unit/DB.spec.ts
  test/unit/Parser.spec.ts
Labels: breaking, in progress

#869 fix: use integer satoshi quantities
  .gitattributes
  docs/api.md
  lib/cli/commands/executeswap.ts
  lib/cli/commands/listorders.ts
  lib/cli/commands/removeorder.ts
  lib/cli/utils.ts
  lib/db/models/Order.ts
  lib/db/models/SwapDeal.ts
  lib/db/models/Trade.ts
  lib/orderbook/OrderBook.ts
  lib/orderbook/types.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_pb.js
  lib/service/Service.ts
  lib/swaps/Swaps.ts
  proto/xudp2p.proto
  proto/xudrpc.proto
  test/integration/OrderBook.spec.ts
  test/integration/Swaps.spec.ts
  test/simulation/actions.go
  test/simulation/xud_test.go
  test/simulation/xudrpc/README.md
  test/simulation/xudrpc/gen_protos.sh
  test/simulation/xudrpc/xudrpc.pb.go
  test/simulation/xudrpc/xudrpc.proto
  test/unit/Command.spec.ts
  test/unit/DB.spec.ts
  test/unit/Swaps.spec.ts
Labels: breaking, bug, grpc, in progress

#875 style: fix golint errors in simulation tests
  test/simulation/actions.go
  test/simulation/go.mod
  test/simulation/go.sum
  test/simulation/xud_test.go
Labels: code quality, in progress

#878 chore: generate protobuf
  lib/proto/xudp2p_pb.d.ts
  lib/proto/xudp2p_pb.js
  package.json
Labels: in progress

#855 feat(orderbook): require token address for Raiden currencies
  lib/orderbook/OrderBook.ts
  lib/orderbook/errors.ts
Labels: in progress

#880 fix(orderbook): rename SwapClients to SwapClient
  lib/orderbook/OrderBook.ts
Labels: in progress

#876 fix(p2p): NodeStateUpdatePacket process crash
  lib/p2p/Pool.ts
Labels: bug, in progress, p2p

#887 fix(lndclient): set status disabled when disabled
  lib/lndclient/LndClient.ts
Labels: in progress

#885 refactor: NodeStateUpdate to include all fields
  lib/Xud.ts
  lib/orderbook/OrderBook.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/p2p/packets/types/NodeStateUpdatePacket.ts
  lib/p2p/packets/types/SessionInitPacket.ts
  lib/p2p/types.ts
  lib/raidenclient/RaidenClient.ts
  test/integration/Pool.spec.ts
  test/p2p/sanity.spec.ts
  test/unit/Parser.spec.ts
Labels: code quality, in progress, p2p

#886 fix(p2p): various reconnection issues
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  test/integration/Pool.spec.ts
Labels: in progress, p2p

#874 feat(raiden): add sendPayment support
  lib/Xud.ts
  lib/constants/enums.ts
  lib/raidenclient/RaidenClient.ts
  lib/raidenclient/errors.ts
  lib/swaps/Swaps.ts
  test/integration/Swaps.spec.ts
Labels: in progress, raiden, swaps

#863 feat(orderbook): add sanity checks to placeOrder
  lib/Config.ts
  lib/Xud.ts
  lib/orderbook/OrderBook.ts
  lib/orderbook/errors.ts
  lib/swaps/Swaps.ts
  sample-xud.conf
  test/integration/OrderBook.spec.ts
  test/integration/Service.spec.ts
  test/simulation/xudtest/node.go
Labels: in progress, order book

#894 test: fix placeOrderAndBroadcast race condition
  test/simulation/actions.go
Labels: automated tests, in progress

#820 Listorders all
  docs/api.md
  lib/cli/commands/listorders.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/Service.ts
  lib/utils/utils.ts
  proto/xudrpc.proto
  test/integration/Service.spec.ts
  test/unit/Command.spec.ts
Labels: in progress

#901 fix(swapclients): check capacity up front
  lib/BaseClient.ts
  lib/Xud.ts
  lib/lndclient/LndClient.ts
  lib/orderbook/OrderBook.ts
  lib/orderbook/errors.ts
  lib/raidenclient/RaidenClient.ts
  package.json
  test/simulation/xud_test.go
  test/simulation/xudtest/node.go
Labels: automated tests, bug, in progress, swaps

#902 chore: disable current v12 node travis build
  .travis.yml
Labels: build, in progress

#906 test: use go 1.12 for simulation tests
  .travis.yml
  test/simulation/README.md
  test/simulation/go.mod
  test/simulation/go.sum
Labels: in progress

#904 refactor(rpc): combine added & removed order calls
  docs/api.md
  lib/cli/commands/streamorders.ts
  lib/grpc/GrpcServer.ts
  lib/grpc/GrpcService.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_grpc_pb.d.ts
  lib/proto/xudrpc_grpc_pb.js
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/Service.ts
  proto/xudrpc.proto
  test/simulation/actions.go
  test/simulation/xud_test.go
  test/simulation/xudrpc/xudrpc.pb.go
Labels: grpc, in progress, order book

#905 Readme documentation fix, xud-simulation readme addon
  README.md
  test/simulation/README.md
Labels: in progress

#908 feat(rpc): removed own orders in SubscribeOrders
  lib/orderbook/OrderBook.ts
  lib/orderbook/TradingPair.ts
  lib/service/Service.ts
Labels: grpc, in progress, order book

#916 test: simulation framework refactoring, p2p scenarios
  .travis.yml
  lib/grpc/GrpcServer.ts
  lib/p2p/Pool.ts
  package.json
  test/simulation/README.md
  test/simulation/actions.go
  test/simulation/config.go
  test/simulation/harnessTest.go
  test/simulation/lntest/harness.go
  test/simulation/tests.go
  test/simulation/xud_test.go
  test/simulation/xudtest/harness.go
  test/simulation/xudtest/node.go
Labels: automated tests, in progress, p2p
