Repository ExchangeUnion/xud, pull requests merged in 2019-05, with the labels that each got.

#907 refactor: node file system API
  lib/Config.ts
  lib/db/DB.ts
  lib/grpc/GrpcServer.ts
  lib/grpc/webproxy/GrpcWebProxyServer.ts
  lib/lndclient/LndClient.ts
  lib/nodekey/NodeKey.ts
  lib/utils/fsUtils.ts
Labels: code quality, in progress, low priority

#937 fix: switch swap capacity check currency
  lib/orderbook/OrderBook.ts
  lib/swaps/Swaps.ts
  test/simulation/tests.go
  test/unit/Swaps.spec.ts
Labels: bug

#936 docs: clarifying code and adding comments
  lib/grpc/GrpcService.ts
  lib/orderbook/OrderBook.ts
  lib/orderbook/TradingPair.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/p2p/packets/Packet.ts
  lib/p2p/types.ts
  lib/service/Service.ts
  test/integration/OrderBook.spec.ts
  test/integration/Service.spec.ts
  test/unit/TradingPair.spec.ts
Labels: documentation

#928 chore: incremental builds & typescript 3.4
  .gitignore
  lib/p2p/packets/types/SwapFailedPacket.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: build

#949 feat(raiden): pass secret hash to raiden
  lib/raidenclient/RaidenClient.ts
  lib/raidenclient/types.ts
Labels: raiden

#939 refactor: enable noUnusedLocals tsconfig option
  lib/Xud.ts
  lib/cli/commands/listorders.ts
  lib/grpc/GrpcService.ts
  lib/orderbook/OrderBook.ts
  lib/orderbook/OrderBookRepository.ts
  lib/p2p/NodeList.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/p2p/packets/types/PongPacket.ts
  lib/raidenclient/RaidenClient.ts
  lib/service/Service.ts
  lib/swaps/Swaps.ts
  test/crypto/handshake.ts
  test/integration/OrderBook.spec.ts
  test/unit/DB.spec.ts
  test/unit/Swaps.spec.ts
  test/unit/uriUtils.spec.ts
  tsconfig.json
Labels: code quality

#923 feat(lnd): use lnd 0.6.1 w/ hold invoices
  docs/api.md
  lib/Xud.ts
  lib/cli/commands/addcurrency.ts
  lib/constants/enums.ts
  lib/db/DB.ts
  lib/grpc/GrpcServer.ts
  lib/grpc/GrpcService.ts
  lib/lndclient/LndClient.ts
  lib/lndclient/types.ts
  lib/orderbook/OrderBook.ts
  lib/orderbook/types.ts
  lib/p2p/Parser.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/p2p/packets/PacketType.ts
  lib/p2p/packets/types/SanitySwapAckPacket.ts
  lib/p2p/packets/types/SanitySwapInitPacket.ts
  lib/p2p/packets/types/SanitySwapPacket.ts
  lib/p2p/packets/types/SwapFailedPacket.ts
  lib/p2p/packets/types/index.ts
  lib/proto/lndinvoices_grpc_pb.d.ts
  lib/proto/lndinvoices_grpc_pb.js
  lib/proto/lndinvoices_pb.d.ts
  lib/proto/lndinvoices_pb.js
  lib/proto/lndrpc_grpc_pb.d.ts
  lib/proto/lndrpc_grpc_pb.js
  lib/proto/lndrpc_pb.d.ts
  lib/proto/lndrpc_pb.js
  lib/proto/xudp2p_pb.d.ts
  lib/proto/xudp2p_pb.js
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/raidenclient/RaidenClient.ts
  lib/service/Service.ts
  lib/swaps/SwapClient.ts
  lib/swaps/Swaps.ts
  lib/utils/utils.ts
  package.json
  proto/lndinvoices.proto
  proto/lndrpc.proto
  proto/xudp2p.proto
  proto/xudrpc.proto
  test/integration/OrderBook.spec.ts
  test/integration/Service.spec.ts
  test/integration/Swaps.spec.ts
  test/simulation/clean.sh
  test/simulation/install.sh
  test/simulation/lntest/harness.go
  test/simulation/lntest/node.go
  test/simulation/tests.go
  test/simulation/xud_test.go
  test/simulation/xudrpc/gen_protos.sh
  test/simulation/xudrpc/xudrpc.pb.go
  test/simulation/xudtest/node.go
  test/unit/DB.spec.ts
  test/unit/Parser.spec.ts
Labels: in progress, lightning, swaps

#940 Raiden resolver http endpoint
  bin/xud
  lib/Config.ts
  lib/Logger.ts
  lib/Xud.ts
  lib/grpc/GrpcServer.ts
  lib/grpc/GrpcService.ts
  lib/http/HttpServer.ts
  lib/http/HttpService.ts
  lib/p2p/Pool.ts
  lib/proto/hash_resolver_grpc_pb.d.ts
  lib/proto/hash_resolver_grpc_pb.js
  lib/proto/hash_resolver_pb.d.ts
  lib/proto/hash_resolver_pb.js
  lib/raidenclient/RaidenClient.ts
  lib/raidenclient/types.ts
  lib/service/Service.ts
  lib/swaps/Swaps.ts
  lib/swaps/types.ts
  package.json
  proto/hash_resolver.proto
  test/unit/HttpServer.spec.ts
Labels: raiden, swaps

#927 style: fix golint & go vet warnings
  test/simulation/go.mod
  test/simulation/go.sum
  test/simulation/lntest/harness.go
  test/simulation/lntest/node.go
  test/simulation/xud_test.go
  test/simulation/xudtest/harness.go
  test/simulation/xudtest/node.go
Labels: code quality

#963 fix(swaps): don't retry verified currency sanity
  lib/orderbook/OrderBook.ts
  lib/p2p/Peer.ts
Labels: bug, swaps

#959 test: preserve xud log files from sim tests
  test/simulation/xudtest/node.go
Labels: automated tests

#962 test: cache lnd & dependencies in travis
  .gitignore
  .travis.yml
  package.json
  test/simulation/README.md
  test/simulation/install.sh
  test/simulation/lntest/node.go
Labels: automated tests, build

#965 Travis install
  .travis.yml
  test/simulation/xudtest/node.go
Labels: build

#950 test: use os-specific temp dir as xudir
  test/integration/WebProxy.spec.ts
  test/p2p/networks.spec.ts
  test/p2p/sanity.spec.ts
  test/utils.ts
Labels: automated tests

#920 feat: discover nodes from a specific peer
  docs/api.md
  lib/cli/commands/discovernodes.ts
  lib/grpc/GrpcServer.ts
  lib/grpc/GrpcService.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_grpc_pb.d.ts
  lib/proto/xudrpc_grpc_pb.js
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/Service.ts
  proto/xudrpc.proto
Labels: grpc, in progress, p2p

#969 chore: update tslint packages
  lib/cli/command.ts
  lib/grpc/webproxy/GrpcWebProxyServer.ts
  lib/lndclient/LndClient.ts
  lib/orderbook/errors.ts
  lib/p2p/Framer.ts
  lib/p2p/errors.ts
  lib/raidenclient/RaidenClient.ts
  lib/swaps/Swaps.ts
  package-lock.json
  package.json
  tasks/config/sample.ts
  test/p2p/sanity.spec.ts
  test/unit/Parser.spec.ts
  test/unit/Swaps.spec.ts
Labels: build, code quality

#941 fix(tests): make testNetworkInit wait for synced chains
  test/simulation/config.go
  test/simulation/tests.go
Labels: automated tests

#918 refactor: swap client management
  jest.config.js
  lib/Config.ts
  lib/Logger.ts
  lib/Xud.ts
  lib/constants/errorCodesPrefix.ts
  lib/grpc/GrpcService.ts
  lib/lndclient/LndClient.ts
  lib/lndclient/types.ts
  lib/orderbook/OrderBook.ts
  lib/orderbook/errors.ts
  lib/raidenclient/RaidenClient.ts
  lib/service/Service.ts
  lib/swaps/SwapClientManager.ts
  lib/swaps/Swaps.ts
  lib/swaps/errors.ts
  lib/swaps/types.ts
  package-lock.json
  package.json
  test/integration/OrderBook.spec.ts
  test/integration/Service.spec.ts
  test/integration/Swaps.spec.ts
  test/jest/SwapClientManager.spec.ts
Labels: in progress

#968 fix(swaps): remove stalled sanity swap invoice
  lib/p2p/Pool.ts
  lib/swaps/Swaps.ts
Labels: bug, swaps

#975 fix: load raiden token addresses from db
  lib/Xud.ts
  lib/swaps/SwapClientManager.ts
  test/jest/SwapClientManager.spec.ts
Labels: bug, raiden

#985 fix: calculate swap amount for market orders
  lib/db/models/Order.ts
  lib/orderbook/OrderBook.ts
  lib/swaps/Swaps.ts
  test/unit/DB.spec.ts
  test/unit/Swaps.spec.ts
Labels: bug

#994 test(orderbook): add insufficient outbound balance check
  package.json
  test/jest/Orderbook.spec.ts
  test/jest/__snapshots__/Orderbook.spec.ts.snap
Labels: order book

#1001 refactor: make peer activePairs private
  lib/orderbook/OrderBook.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  test/jest/Orderbook.spec.ts
Labels: code quality

#997 fix(swaps): prevent SwapFailurePacket crash
  lib/swaps/Swaps.ts
Labels: bug, error handling

#993 feat(raiden): log error message for 409 responses
  lib/raidenclient/RaidenClient.ts
  lib/raidenclient/errors.ts
Labels: logging, raiden
