Repository ExchangeUnion/xud, pull requests merged in 2020-01, with the labels that each got.

#1350 refactor(cli): handle stream error event
  lib/cli/commands/streamorders.ts
  lib/cli/placeorder.ts
Labels: command line (CLI), error handling

#1352 feat: restore from backup
  docs/api.md
  lib/Xud.ts
  lib/backup/Backup.ts
  lib/cli/commands/restore.ts
  lib/grpc/GrpcInitService.ts
  lib/lndclient/LndClient.ts
  lib/nodekey/NodeKey.ts
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/InitService.ts
  lib/swaps/SwapClientManager.ts
  lib/utils/seedutil.ts
  lib/utils/utils.ts
  npm-shrinkwrap.json
  package.json
  proto/xudrpc.proto
  seedutil/SeedUtil.spec.ts
  seedutil/__snapshots__/SeedUtil.spec.ts.snap
  seedutil/main.go
  test/jest/Backup.spec.ts
  test/jest/NodeKey.spec.ts
  test/unit/NodeKey.spec.ts
Labels: P1

#1359 Backup related fixes
  lib/backup/Backup.ts
  lib/lndclient/LndClient.ts
  test/jest/Backup.spec.ts
Labels: lightning

#1363 feat(lnd): retry init if misconfigured (WIP)
  lib/lndclient/LndClient.ts
  lib/swaps/SwapClient.ts
  test/integration/Service.spec.ts
Labels: lightning

#1283 refactor(cli): hide executeswap command
  lib/cli/commands/executeswap.ts
Labels: command line (CLI), enhancement, review required

#1366 refactor(lnd): lock on any unimplemented error
  lib/lndclient/LndClient.ts
Labels: P1, lightning

#1374 fix(lnd): prevent undefined error
  lib/lndclient/LndClient.ts
Labels: P2, bug, lightning

#1377 fix(cli): print UNAVAILABLE errors correctly
  lib/cli/command.ts
Labels: bug, command line (CLI), error handling

#1372 fix(rpc/lnd): lnd already unlocked
  lib/swaps/SwapClientManager.ts
Labels: P2, grpc, lightning

#1373 test: fix nodekey edge case
  test/jest/NodeKey.spec.ts
Labels: automated tests

#1365 refactor: close misconfigured SwapClients
  lib/lndclient/LndClient.ts
  lib/raidenclient/RaidenClient.ts
  lib/service/InitService.ts
  lib/swaps/SwapClient.ts
  lib/swaps/SwapClientManager.ts
Labels: P3, code quality

#1380 feat(cli): better messages when unlock/create fail
  lib/Xud.ts
  lib/cli/command.ts
  lib/grpc/GrpcInitService.ts
  lib/grpc/getGrpcError.ts
  lib/service/InitService.ts
  lib/service/errors.ts
Labels: command line (CLI), error handling

#1375 refactor(p2p): use PeerStatus enum
  lib/p2p/Peer.ts
Labels: code quality, p2p

#1378 refactor: set swap client disconnected on timeout
  lib/swaps/SwapClient.ts
Labels: lightning

#1381 feat(rpc): wrong password error for unlock
  lib/service/InitService.ts
Labels: error handling, grpc

#1376 feat: use seedutil to generate mnemonic
  lib/service/InitService.ts
  lib/swaps/SwapClientManager.ts
  lib/utils/seedutil.ts
  seedutil/SeedUtil.spec.ts
  seedutil/main.go
Labels: enhancement
