Repository ExchangeUnion/xud, pull requests merged in 2020-02, with the labels that each got.

#1383 refactor(lnd): remove unused genSeed code
  lib/lndclient/LndClient.ts
Labels: lightning

#1386 chore: disable raiden simulation tests
  test/simulation/actions.go
  test/simulation/install.sh
  test/simulation/tests-integration.go
  test/simulation/xud_test.go
Labels: automated tests

#1357 Dockerized simulation tests
  .gitignore
  .travis.yml
  package.json
  test/simulation/.env
  test/simulation/Dockerfile
  test/simulation/Dockerfile_gomod
  test/simulation/actions.go
  test/simulation/address-to-eip55.sh
  test/simulation/attach-geth.sh
  test/simulation/cleanup-processes.sh
  test/simulation/create-ethereum-account.sh
  test/simulation/create-geth-genesis.sh
  test/simulation/create-raiden-config.sh
  test/simulation/deploy-contracts.sh
  test/simulation/docker-btcd/Dockerfile
  test/simulation/docker-build.sh
  test/simulation/docker-clean.sh
  test/simulation/docker-compose.yml
  test/simulation/docker-lnd/Dockerfile
  test/simulation/docker-lnd/install-lnd.sh
  test/simulation/docker-run.sh
  test/simulation/generate-ethereum-blocks.sh
  test/simulation/get-alice-channels.sh
  test/simulation/get-bob-channels.sh
  test/simulation/install-ethereum-utils.sh
  test/simulation/install-ethereum.sh
  test/simulation/install-geth.sh
  test/simulation/install-raiden-contracts.sh
  test/simulation/install-raiden.sh
  test/simulation/install-solc.sh
  test/simulation/install.sh
  test/simulation/lntest/node.go
  test/simulation/raiden-config-template.toml
  test/simulation/start-autominer.sh
  test/simulation/start-geth.sh
  test/simulation/start-raiden-alice.sh
  test/simulation/start-raiden-bob.sh
  test/simulation/start-raiden.sh
  test/simulation/tests-integration.go
  test/simulation/utils/create-account.js
  test/simulation/utils/ethereum/eip55.py
  test/simulation/utils/ethereum/geth-autominer.py
  test/simulation/utils/ethereum/requirements.txt
  test/simulation/utils/genesis.json
  test/simulation/xud_test.go
  test/simulation/xudtest/harness.go
Labels: P1

#1389 chore: run 'npm audit fix'
  npm-shrinkwrap.json
Labels: build

#1388 chore: slate script
  .gitignore
  docs/api.md
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_grpc_pb.d.ts
  lib/proto/xudrpc_grpc_pb.js
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  npm-shrinkwrap.json
  package.json
  proto/xudrpc.proto
Labels: build, documentation

#1391 chore: ignore simulation temp directory
  .gitignore
Labels: build

#1387 feat(p2p): add p2p tor config option
  bin/xud
  lib/Config.ts
  lib/grpc/getGrpcError.ts
  lib/p2p/Pool.ts
  lib/p2p/errors.ts
  lib/p2p/types.ts
  test/integration/Pool.spec.ts
Labels: p2p

#1347 feat: disable raiden currencies w/out direct chan
  lib/constants/enums.ts
  lib/orderbook/OrderBook.ts
  lib/p2p/Peer.ts
  lib/swaps/SwapClientManager.ts
  lib/swaps/Swaps.ts
  test/integration/OrderBook.spec.ts
  test/integration/Swaps.spec.ts
  test/jest/Orderbook.spec.ts
Labels: P2, order book, raiden

#1390 chore: generate slate on new version
  package.json
Labels: build

#1393 test: simtest to use lnd 0.9.0-beta
  test/simulation/docker-lnd/Dockerfile
Labels: automated tests

#1394 fix(lnd): auto unlock consistently
  lib/lndclient/LndClient.ts
Labels: bug, lightning

#1395 feat(peer): add native tor support
  bin/xud
  lib/Config.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/p2p/types.ts
  npm-shrinkwrap.json
  package.json
  sample-xud.conf
  test/jest/Pool.spec.ts
Labels: p2p

#1397 fix(swaps): only query routes for connected swap clients
  lib/swaps/SwapClientManager.ts
Labels: bug, raiden

#1400 refactor: log unhandled rejection to stderr
  lib/bootstrap.ts
Labels: logging

#1401 test: don't allocUnsafe for NodeKey tests
  test/jest/NodeKey.spec.ts
Labels: automated tests

#1402 perf(rpc/orderbook): listorders array concatenation
  lib/service/Service.ts
Labels: grpc, performance

#1398 refactor: only verify peer currencies if connected
  lib/orderbook/OrderBook.ts
  lib/swaps/SwapClientManager.ts
  test/jest/Orderbook.spec.ts
Labels: swaps

#1403 test: fix simtest infra
  package.json
  test/simulation/Dockerfile
  test/simulation/actions.go
  test/simulation/docker-clean.sh
  test/simulation/docker-run.sh
  test/simulation/go.mod
  test/simulation/logs.sh
  test/simulation/tests-instability.go
  test/simulation/xud_test.go
  test/simulation/xudtest/node.go
Labels: automated tests

#1404 chore: update typescript
  npm-shrinkwrap.json
  package.json
Labels: build

#1399 refactor: organize/clarify canRouteToPeer logic
  lib/lndclient/LndClient.ts
  lib/orderbook/OrderBook.ts
  lib/raidenclient/RaidenClient.ts
  lib/swaps/SwapClient.ts
  lib/swaps/SwapClientManager.ts
  test/jest/Orderbook.spec.ts
Labels: code quality, swaps

#1392 feat(rpc): add owner parameter for listorders
  docs/api.md
  lib/cli/commands/listorders.ts
  lib/cli/commands/orderbook.ts
  lib/constants/enums.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/Service.ts
  proto/xudrpc.proto
  test/integration/Service.spec.ts
  test/jest/Service.spec.ts
Labels: grpc

#1382 feat(config): property type and value checking
  lib/Config.ts
  lib/Xud.ts
  test/jest/Config.spec.ts
Labels: configuration, error handling

#1409 refactor(swapclient): status and initialization
  lib/Xud.ts
  lib/backup/Backup.ts
  lib/lndclient/LndClient.ts
  lib/raidenclient/RaidenClient.ts
  lib/service/Service.ts
  lib/swaps/SwapClient.ts
  lib/swaps/SwapClientManager.ts
  lib/swaps/Swaps.ts
  test/jest/RaidenClient.spec.ts
  test/jest/SwapClientManager.spec.ts
Labels: code quality, lightning, raiden

#1413 test(sim): decouple nvm/xud installation from the test files image
  .gitignore
  package.json
  test/simulation/Dockerfile
  test/simulation/docker-compose.yml
  test/simulation/docker-xud/Dockerfile
  test/simulation/xudtest/harness.go
Labels: automated tests
