Repository ExchangeUnion/xud, pull requests merged in 2020-03, with the labels that each got.

#1429 style: add linting rules
  lib/Xud.ts
  lib/cli/commands/getinfo.ts
  lib/cli/commands/listpeers.ts
  lib/cli/commands/orderbook.ts
  lib/cli/commands/streamorders.ts
  lib/constants/limits.ts
  lib/db/models/Order.ts
  lib/db/models/SwapDeal.ts
  lib/db/models/Trade.ts
  lib/grpc/getGrpcError.ts
  lib/orderbook/OrderBook.ts
  lib/orderbook/TradingPair.ts
  lib/p2p/Parser.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  lib/p2p/packets/Packet.ts
  lib/swaps/Swaps.ts
  lib/swaps/types.ts
  test/integration/OrderBook.spec.ts
  test/jest/WebProxy.spec.ts
  test/p2p/sanity.spec.ts
  test/unit/Parser.spec.ts
  tslint.json
Labels: code quality

#1432 test(sim): lock btcd version
  test/simulation/docker-btcd/Dockerfile
Labels: automated tests, build

#1421 test(sim): update npm scripts & README.md
  .travis.yml
  package.json
  test/simulation/README.md
  test/simulation/docker-build.sh
Labels: automated tests, documentation

#1430 feat(swapclient): add Locked status
  lib/lndclient/LndClient.ts
  lib/swaps/SwapClient.ts
Labels: lightning, swaps

#1435 refactor(swapclients): currency:client type check
  lib/raidenclient/RaidenClient.ts
  lib/swaps/SwapClientManager.ts
Labels: swaps

#1434 fix: allow unlock with disconnected lnd
  lib/service/InitService.ts
Labels: lightning

#1441 fix(lnd): exponential backoff for grpc client wait
  lib/lndclient/LndClient.ts
Labels: lightning

#1438 test(sim): wait until xud finish initializing
  test/simulation/xud_test.go
  test/simulation/xudtest/node.go
Labels: automated tests

#1439 test(sim): adjust ctx deadline
  test/simulation/harnessTest.go
  test/simulation/tests-instability.go
  test/simulation/tests-security.go
  test/simulation/xud_test.go
  test/simulation/xudtest/harness.go
Labels: automated tests

#1442 fix(lnd): don't check for manual unlock
  lib/lndclient/LndClient.ts
Labels: lightning

#1445 chore: automatically generate sim test protos
  .gitattributes
  package.json
  proto/README.md
  test/simulation/xudrpc/annotations.proto
  test/simulation/xudrpc/gen_protos.sh
  test/simulation/xudrpc/google/api/http.proto
  test/simulation/xudrpc/google/protobuf/descriptor.proto
  test/simulation/xudrpc/xudrpc.pb.go
Labels: automated tests, build

#1418 chore: build sim test images on version
  package.json
Labels: build

#1286 feat: different gRPC & HTTP port depending on active network
  lib/Config.ts
  test/jest/Config.spec.ts
Labels: enhancement, review required

#1440 test(sim): export lnd instances logs
  test/simulation/lntest/node.go
  test/simulation/logs.sh
Labels: automated tests

#1444 chore: ignore xud docker sim test directory
  .gitignore
Labels: automated tests

#1447 1.0.0 beta.2
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
  sample-xud.conf
Labels: build
