Repository ExchangeUnion/xud, pull requests merged in 2020-11, with the labels that each got.

#1950 fix(cli): openchannel assertion error for string amount
  lib/cli/commands/openchannel.ts
Labels: command line (CLI)

#1746 feat(rpc): runtime addcurrency for lnd & connext
  lib/orderbook/OrderBook.ts
  lib/p2p/Pool.ts
  lib/swaps/SwapClientManager.ts
  test/simulation/README.md
  test/simulation/actions.go
  test/simulation/connexttest/harness.go
  test/simulation/tests-instability.go
  test/simulation/tests-integration.go
Labels: P2, grpc

#1942 fix(rpc): no success if no channels to close (#1689)
  lib/connextclient/ConnextClient.ts
  lib/grpc/getGrpcError.ts
  lib/service/Service.ts
  lib/service/errors.ts
Labels: grpc

#1980 refactor(rpc): rename reserved TradingLimits fields
  docs/api.md
  lib/cli/commands/tradinglimits.ts
  lib/grpc/GrpcService.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/swaps/SwapClientManager.ts
  lib/swaps/types.ts
  proto/xudrpc.proto
  test/jest/cli/__snapshots__/tradinglimits.spec.ts.snap
  test/jest/cli/tradinglimits.spec.ts
  test/simulation/xudrpc/xudrpc.pb.go
Labels: grpc

#1962 fix: alias missing in streamorders (#1725)
  lib/grpc/GrpcService.ts
  lib/service/Service.ts
Labels: bug

#1966 feat(lnd): change gRPC client options
  lib/lndclient/LndClient.ts
Labels: P1

#1964 fix: tls certificate check on startup (#1510)
  lib/cli/command.ts
Labels: bug

#1969 fix(lnd): handling hold invoice check errors
  lib/lndclient/LndClient.ts
  lib/swaps/SwapClient.ts
Labels: bug, error handling, lightning

#1971 feat(lnd): SendPaymentV2
  lib/lndclient/LndClient.ts
  lib/proto/lndrouter_grpc_pb.d.ts
  lib/proto/lndrouter_grpc_pb.js
  lib/proto/lndrouter_pb.d.ts
  lib/proto/lndrouter_pb.js
  lib/proto/lndrpc_grpc_pb.d.ts
  lib/proto/lndrpc_grpc_pb.js
  lib/proto/lndrpc_pb.d.ts
  lib/proto/lndrpc_pb.js
  lib/proto/lndwalletunlocker_grpc_pb.d.ts
  lib/proto/lndwalletunlocker_grpc_pb.js
  lib/proto/lndwalletunlocker_pb.d.ts
  lib/proto/lndwalletunlocker_pb.js
  lib/swaps/Swaps.ts
  lib/swaps/consts.ts
  lib/utils/utils.ts
  proto/lndrouter.proto
  proto/lndrpc.proto
  proto/lndwalletunlocker.proto
  test/jest/LndClient.spec.ts
  test/jest/__snapshots__/LndClient.spec.ts.snap
  test/simulation/docker-lnd/Dockerfile
Labels: lightning

#1988 fix(lnd): don't calculate negative capacities
  lib/lndclient/LndClient.ts
Labels: bug, lightning

#1987 fix: use regtest instead of regnet arg
  bin/xud
Labels: bug

#1986 fix: changes removeorder output to a more meaningful message (#1526)
  docs/api.md
  lib/cli/commands/removeorder.ts
  lib/grpc/GrpcService.ts
  lib/orderbook/OrderBook.ts
  lib/proto/annotations_grpc_pb.js
  lib/proto/xudp2p_grpc_pb.js
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  proto/xudrpc.proto
  test/simulation/xudrpc/xudrpc.pb.go
Labels: command line (CLI), enhancement

#1994 fix: graceful shutdown
  lib/connextclient/ConnextClient.ts
  lib/p2p/Peer.ts
  lib/p2p/Pool.ts
  test/jest/Connext.spec.ts
Labels: code quality

#1998 chore(release): 1.2.1
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: build

#2000 feat(rpc): GetMnemonic
  docs/api.md
  lib/Xud.ts
  lib/cli/commands/create.ts
  lib/cli/commands/getmnemonic.ts
  lib/cli/utils.ts
  lib/grpc/GrpcService.ts
  lib/nodekey/NodeKey.ts
  lib/proto/annotations_grpc_pb.js
  lib/proto/xudp2p_grpc_pb.js
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_grpc_pb.d.ts
  lib/proto/xudrpc_grpc_pb.js
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/Service.ts
  lib/service/types.ts
  lib/swaps/SwapClientManager.ts
  proto/xudrpc.proto
  test/jest/Service.spec.ts
  test/simulation/xudrpc/xudrpc.pb.go
Labels: command line (CLI), grpc

#2002 fix: limits account for replaced order quantity
  lib/orderbook/OrderBook.ts
Labels: bug, grpc, order book

#2001 feat: enhance simulation test README
  test/simulation/README.md
Labels: documentation

#2007 feat: change master password
  docs/api.md
  lib/Xud.ts
  lib/cli/command.ts
  lib/cli/commands/changepass.ts
  lib/db/DB.ts
  lib/db/migrations.ts
  lib/db/models/Password.ts
  lib/db/models/index.ts
  lib/db/types.ts
  lib/grpc/GrpcService.ts
  lib/grpc/getGrpcError.ts
  lib/lndclient/LndClient.ts
  lib/nodekey/NodeKey.ts
  lib/p2p/Framer.ts
  lib/proto/xudrpc.swagger.json
  lib/proto/xudrpc_grpc_pb.d.ts
  lib/proto/xudrpc_grpc_pb.js
  lib/proto/xudrpc_pb.d.ts
  lib/proto/xudrpc_pb.js
  lib/service/InitService.ts
  lib/service/Service.ts
  lib/service/errors.ts
  lib/swaps/SwapClientManager.ts
  lib/swaps/Swaps.ts
  lib/utils/cryptoUtils.ts
  lib/utils/utils.ts
  proto/xudrpc.proto
  test/jest/NodeKey.spec.ts
  test/jest/Orderbook.spec.ts
  test/jest/SwapClientManager.spec.ts
  test/jest/cryptoUtils.spec.ts
  test/simulation/xudrpc/xudrpc.pb.go
Labels: enhancement, grpc, lightning
